name: claw_app
description: "1Claw - Multi-Agent Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-153.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.1
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  system_fonts:
    path: ./lib/3rd-party/system_fonts
  flutter_markdown: ^0.7.6
  posh_flutter_components:
    path: ./lib/3rd-party/posh_flutter_components
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^18.0.1
  file_picker: ^11.0.2
  posh_voice_input:
    path: ./lib/3rd-party/posh_voice_input

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
